[versions]
androidMinSdk = "24"
androidCompileSdk = "34"
androidTargetSdk = "34"
kotlinCompilerExtension = "1.5.3"
camera = "1.3.0-rc01"
engine = "1.27.0"
buildConfig = "5.3.5"
dropshots = "0.4.1"
gradleAndroid = "8.3.2"
googleServices = "4.3.15"

[libraries]
cesdk-engine = { group = "ly.img", name = "engine", version.ref = "engine" }
cesdk-engine-camera = { group = "ly.img", name = "engine-camera", version.ref = "engine" }

kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion"

compose-bom = "androidx.compose:compose-bom:2023.05.01"
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-activity = "androidx.activity:activity-compose:1.6.1"
compose-navigation = "androidx.navigation:navigation-compose:2.5.3"
compose-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1"
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

coil-compose = "io.coil-kt:coil-compose:2.2.2"

material = "com.google.android.material:material:1.8.0"

colormath = "com.github.ajalt.colormath:colormath:3.2.1"
colormath-compose = "com.github.ajalt.colormath.extensions:colormath-ext-jetpack-compose:3.2.1"

shimmer = "com.valentinilk.shimmer:compose-shimmer:1.0.5"

camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "camera" }

test-androidx-runner = { group = "androidx.test", name = "runner", version.strictly = "1.5.2" }
